development:
  adapter: sqlite3
  database: db/development_demo.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test_demo.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production_demo.sqlite3
  pool: 5
  timeout: 5000